version: 1.0.{build}
configuration: release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
services:
  - mssql2014
before_build:
- cmd: for /R %%f in (*.sln) do nuget restore "%%f"
- ps: >-
    Invoke-WebRequest -Uri https://download.microsoft.com/download/f/d/8/fd8c20d8-e38a-48b6-8691-542403b91da1/AccessDatabaseEngine.exe -OutFile ./ACE.exe
    Start-Process .\ACE.exe -ArgumentList "/quiet"
build:
  project: JsPlc.Ssc.PetrolPricing\PetrolPricing.sln
  publish_wap: true
deploy:
- provider: Environment
  name: petrolpricing-development
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: petrolpricing
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
