version: 1.0.{build}
configuration: release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
services:
  - mssql2012
before_build:
- cmd: for /R %%f in (*.sln) do nuget restore "%%f"
- ps: >-
    Invoke-WebRequest -Uri https://download.microsoft.com/download/f/d/8/fd8c20d8-e38a-48b6-8691-542403b91da1/AccessDatabaseEngine.exe -OutFile AccessDatabaseEngine.exe

    Start-Process AccessDatabaseEngine.exe -ArgumentList "/quiet" -Wait
build:
  project: JsPlc.Ssc.PetrolPricing\PetrolPricing.sln
  publish_wap: true
after_build:
- cmd: >-
    7z a JsPlc.Ssc.PetrolPricing.IntegrationTests.zip %APPVEYOR_BUILD_FOLDER%\JsPlc.Ssc.PetrolPricing\JsPlc.Ssc.PetrolPricing.IntegrationTests\bin\x86\Release\*.*
    
    AppVeyor PushArtifact JsPlc.Ssc.PetrolPricing.IntegrationTests.zip -DeploymentName JsPlc.Ssc.PetrolPricing.IntegrationTests
artifacts:
- path: JsPlc.Ssc.PetrolPricing\JsPlc.Ssc.PetrolPricing.Databases\PetrolPricingRepository\bin\Release\PetrolPricingRepository.dacpac
  name: JsPlc.Ssc.PetrolPricing.Databases
deploy:
- provider: SqlDatabase
  artifact: JsPlc.Ssc.PetrolPricing.Databases
  connection_string: 'Server=(local)\SQL2014;Database=my_test_db;User ID=sa;Password=Password12!'
test:
  assemblies:
    - '**\*.*tests.dll'
deploy:
- provider: Environment
  name: petrolpricing-development
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: petrolpricing
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
