version: 1.0.{build}
configuration: release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
services:
  - mssql2012
before_build:
- cmd: for /R %%f in (*.sln) do nuget restore "%%f"
- ps: >-
    Invoke-WebRequest -Uri https://download.microsoft.com/download/f/d/8/fd8c20d8-e38a-48b6-8691-542403b91da1/AccessDatabaseEngine.exe -OutFile AccessDatabaseEngine.exe

    Start-Process AccessDatabaseEngine.exe -ArgumentList "/quiet" -Wait
build:
  project: JsPlc.Ssc.PetrolPricing\PetrolPricing.sln
  publish_wap: true
before_test:
- ps: >-
    $configFile = "$env:APPLICATION_PATH\app.config"

    [xml] $xmlfile = Get-Content $configFile

    write-host "Transforming the config file" $configFile

    foreach ($item in $xmlfile.configuration.appSettings){
      if($item.add.key -eq "ServicesBaseUrl"){
        write-host "Updating the connection string to " $env:ServicesBaseUrlAppConfig
        $item.add.value = $env:ServicesBaseUrlAppConfig
      }
    }

    $xmlfile.Save( (Resolve-Path($configFile)))

    write-host "Transformation completed."
artifacts:
- path: JsPlc.Ssc.PetrolPricing\JsPlc.Ssc.PetrolPricing.Databases\PetrolPricingRepository\bin\Release\PetrolPricingRepository.dacpac
  name: JsPlc.Ssc.PetrolPricing.Databases
deploy:
- provider: Environment
  name: petrolpricing-development
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: petrolpricing
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
