//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsPlc.Ssc.PetrolPricing.Portal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsPlc.Ssc.PetrolPricing.Portal.StringMessages", typeof(StringMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format for Daily Price Data file. Expected format is CSV in a simple text file..
        /// </summary>
        public static string Error_InvalidFileFormat_DailyPriceData {
            get {
                return ResourceManager.GetString("Error_InvalidFileFormat_DailyPriceData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid file format for Quarterly Price Data file. Expected format is CSV in a simple text file..
        /// </summary>
        public static string Error_InvalidFileFormat_QuarterlyPriceData
        {
            get {
                return ResourceManager.GetString("Error_InvalidFileFormat_QuarterlyPriceData", resourceCulture);
            }
        }
              
       
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid upload file. Please retry and select a file to upload.
        /// </summary>
        public static string Error_InvalidUploadFile {
            get {
                return ResourceManager.GetString("Error_InvalidUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be uploaded. Please retry the upload..
        /// </summary>
        public static string Error_ReuploadFile {
            get {
                return ResourceManager.GetString("Error_ReuploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please try again..
        /// </summary>
        public static string Error_TryAgain {
            get {
                return ResourceManager.GetString("Error_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file is empty or no file selected. Please select a file to upload.
        /// </summary>
        public static string Error_UploadedFileIsEmpty {
            get {
                return ResourceManager.GetString("Error_UploadedFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file length should less than 3MB. Please select a file to upload.
        /// </summary>
        public static string Error_UploadedFileLengthGreaterThanMaxSize {
            get {
                return ResourceManager.GetString("Error_UploadedFileLengthGreaterThanMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Today Daily Prices file has already been uploaded..
        /// </summary>
        public static string Warning_DailyPriceFileAlreadyUploaded {
            get {
                return ResourceManager.GetString("Warning_DailyPriceFileAlreadyUploaded", resourceCulture);
            }
        }
    }
}
